import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-900 text-white py-5 shadow-md">
        <div className="container mx-auto px-6 flex justify-between items-center">
          <h1 className="text-2xl md:text-3xl font-bold">Samra Blog</h1>
          <nav className="hidden md:flex gap-6">
            <Link href="/" className="hover:text-gray-200">Home</Link>
            <Link href="/contact" className="hover:text-gray-200">Contact</Link>
          </nav>
          <button className="md:hidden text-white focus:outline-none">
            ☰
          </button>
        </div>
      </header>
        {children}
        <footer className="bg-gray-900 text-white py-6 mt-10 text-center">
        <p>&copy; {new Date().getFullYear()} Samra Blog. All rights reserved.</p>
      </footer>
      </body>
    </html>
  );
}
